[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp","--api-key", "ctx7sk-15d76eab-e479-491d-8a8f-4eabc86f11c7"]

[mcp_servers.shadcn]
command = "npx"
args = ["-y", "mcp-remote", "https://www.shadcn.io/api/mcp"]

