
version: "3.9"
services:
  api:
    build:
      context: ./src/Imperium.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
